name: bookinghomestay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # ğŸ§© Há»— trá»£ ngÃ´n ngá»¯ (DatePicker, v.v.)
  flutter_localizations:
    sdk: flutter
  
  # Firebase core + authentication + Firestore
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # ÄÄƒng nháº­p Google vÃ  Facebook
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1

  # CÃ¡c thÆ° viá»‡n tiá»‡n Ã­ch khÃ¡c
  
  url_launcher: ^6.3.2

  # Hiá»‡u á»©ng hoáº¡t hÃ¬nh Lottie
  lottie: ^3.1.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
